# This is a basic workflow to help you get started with Actions
# Nama workflow CI untuk karsajobs

name: karsajobs-ci

# Mengatur kapan jalannya workflow CI ini yaitu ketika push dilakukan ke branch karsajobs
on: 
  push:
    branches: karsajobs

# List jobs yang dilakukan di dalam workflow CI ini
jobs:
  # Mendefinisikan jobs untuk melakukan lint pada dockerfile
  lint-dockerfile:
    # Job ini akan dijalankan di mesin ubuntu
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dilakukan sebagai bagian dari job
    steps:
      # Melakukan checkout branch saat ini
      - uses: actions/checkout@v4
      # Memberikan nama untuk langkah yang akan dilakukan
      - name: Install hadolint dari github
        # Menjalankan perintah untuk menginstall hadolint dari github
        run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin/hadolint
      - name: Menjalankan hadolint
        # Menjalankan perintah untuk melakukan lint kepada dockerfile menggunakan hadolint
        run: hadolint Dockerfile

  test-app:
    runs-on: ubuntu-latest
    steps:
      # Melakukan checkout branch saat ini
      - uses: actions/checkout@v4
      # Setup untuk menggunakan Go versi 1.15
      - name: Setup versi Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'
      # Menjalankan go test
      - name: Run tests 
        run: go test -v -short --count=1 $(go list ./...)

  # Mendefinisikan jobs untuk melakukan build app
  build-app-karsajobs:
    # Job ini akan dijalankan di mesin ubuntu
    runs-on: ubuntu-latest
    # Job ini akan dijalankan setelah job lint-dockerfile dan test-app selesai
    needs: [lint-dockerfile, test-app]

    # Langkah-langkah yang akan dilakukan sebagai bagian dari job
    steps:
      # Melakukan checkout branch saat ini
      - uses: actions/checkout@v4
      # Memberikan nama untuk langkah yang akan dilakukan
      - name: Build app
        # Menjalankan perintah untuk menjalankan file shell script build image
        run: |
          chmod +x ./build_push_image_karsajobs.sh
          ./build_push_image_karsajobs.sh
        # Mendefinisikan env untuk shell script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
